### ISSUE TITLE
About some label problems

### ISSUE THREAD

**Issue by Azong-HQU** [bytedance/FreeSeg#2]
作者您好！我按照如下操作进行转换数据格式（没改任何代码），但处理完后没有生成这个文件'datasets/coco/stuffthingmaps_panoptic_detectron2/train2017_base_label_count.json'，导致在执行train_prompt阶段无法顺利进行，在“mask2former/data/datasets/register_coco_full.py”文件中的第233行 提示缺失上述json文件！请问作者能否提供我一些改进方法，帮助我解决这个问题？万分感谢！！！
```bash
python datasets/prepare_coco_alldata.py datasets/coco

python datasets/prepare_coco_stuff_164k_sem_seg.py datasets/coco

python tools/mask_cls_collect.py datasets/coco/stuffthingmaps_detectron2/train2017_base datasets/coco/stuffthingmaps_detectron2/train2017_base_label_count.json

python tools/mask_cls_collect.py datasets/coco/stuffthingmaps_detectron2/val2017 datasets/coco/stuffthingmaps_detectron2/val2017_label_count.json
```

**Comment by FreeSeg** [comment]
You can change the bash command from "datasets/coco/stuffthingmaps_detectron2/train2017_base_label_count.json" to "datasets/coco/stuffthingmaps_panoptic_detectron2/train2017_base_label_count.json".
